### ISSUE TITLE
A Directory Traversal vulnerability

### ISSUE THREAD

**Issue by Zh3-H4ck** [FrontAccountingERP/FA#40]
### 0x00 description

Frontaccounting is using the function clean_file_name()  to eliminate '../' in the file name submitted by the user to avoid directory traversal vulnerability.

![2019-11-12_103343](https://user-images.githubusercontent.com/33822448/68640026-74465180-0541-11ea-9472-55c458e23d4c.png)

However, some variables do not use the function clean_file_name() in admin/inst_lang.php, which can cause attackers submit the language package containing the language code of '../'. Affter adding successfully, by deleting it, the attacker can emptied specified folder like the examples.

admin/inst_lang.php:156

![2019-11-12_104009](https://user-images.githubusercontent.com/33822448/68640041-81634080-0541-11ea-99a2-e80748de3051.png)

admin/inst_lang.php:240
![2019-11-12_104205](https://user-images.githubusercontent.com/33822448/68640053-8922e500-0541-11ea-93fa-f75c5f173761.png)

### 0x01 Example:empty admin folder

0. Before clearing the admin folder
![2019-11-12_113112](https://user-images.githubusercontent.com/33822448/68640065-8e802f80-0541-11ea-9d7e-461486d20516.png)

1. The administrator logs in and creates a new language pack
![2019-11-12_112847](https://user-images.githubusercontent.com/33822448/68640076-97710100-0541-11ea-9786-cc14f20fd813.png)
![2019-11-12_112935](https://user-images.githubusercontent.com/33822448/68640080-993ac480-0541-11ea-9366-09cb1cf5514e.png)

2. Set the language code to ../admin and save it
![2019-11-12_113003](https://user-images.githubusercontent.com/33822448/68640086-9c35b500-0541-11ea-93d4-1902a895fe8a.png)

3. Delete the language pack you just created
![2019-11-12_113206](https://user-images.githubusercontent.com/33822448/68640093-9fc93c00-0541-11ea-8d40-156be986b08c.png)

4. After deleting successfully, the admin folder will be emptied
![2019-11-12_113248](https://user-images.githubusercontent.com/33822448/68640098-a35cc300-0541-11ea-9909-7be66130ba7b.png)

**Comment by FrontAccountingERP** [comment]
Yes, indeed. Fix is added to the repo.

**Comment by cambell-prince** [comment]
> Yes, indeed. Fix is added to the repo.

Should this issue be closed?

**Comment by Zh3-H4ck** [comment]
ok
